### ISSUE TITLE
vague "item data empty" error

### ISSUE THREAD

**Issue by garfieldnate** [longkey1/jekyll-amazon-plugin#2]
I used this tag: `{% amazon text 0201799405 %}`, which points to a book called Code Reading. Generation of the page fails with `item data empty asin 0201799405`. As I am sure that the asin is correct, I have no idea how to fix this. I have correct tag, access and password values. It fails with the cache set to `true` or `false` and the country set to `en` or `us`.

**Comment by chauncey-garrett** [comment]
I can confirm that this bug is present as I receive it on certain ASIN values but not on others.

This one works:

    B00KAI3KW2

This one doesn't:

     B00BGA9WK2

After a brief overview of the code, it looks as if some portion of the product's data from Amazon is either not being made available by Amazon or is unintentionally lost from within the code.

**Comment by longkey1** [comment]
fixed this issue!

**Comment by garfieldnate** [comment]
Thanks!
